### ISSUE TITLE
Would it be `seq_len(replicates)` rather than `seq_along(replicates)`

### ISSUE THREAD

**Issue by Yangshen0325** [rsetienne/DAISIE#144]
In DAISIE_sim_cr_iw.R script, line 18
`for (rep in seq_along(replicates)) {...}`
We define replicates as numerical, but by applying seq_along() function to it, you can only get the answer 1. If I understand correctly, **replicates** means how many times the simulation runs. If it is the case, then  it might be `seq_len(replicates)`.

**Comment by Neves-P** [comment]
Hi @Yangshen0325 ,

You're right, the code there should read `seq_len(replicates)` rather than `seq_along(replicates)`. I changed it incorrectly from `1:length(replicates)` and chose the wrong function, thus creating this bug. Well spotted! Feel free to change and push this to a topic branch off of develop and then merge to develop if tests pass.
@rsetienne, I think this should go in an upcoming bugfix release which we can put out shortly if everyone agrees.

**Comment by joshwlambert** [comment]
Made the fix and pushed to the `cont_fix` branch which will later be merged into `develop` and `master` and should close the issue automatically. Thanks for the good spot @Yangshen0325 😄
